# Thai translation for xentaos
# Copyright (c) 2014 Rosetta Contributors and Canonical Ltd 2014
# This file is distributed under the same license as the xentaos package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
msgid ""
msgstr ""
"Project-Id-Version: xentaos\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2017-10-27 12:58+0100\n"
"PO-Revision-Date: 2017-03-26 15:59+0000\n"
"Last-Translator: Rockworld <sumoisrock@gmail.com>\n"
"Language-Team: Thai <th@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2017-11-12 09:53+0000\n"
"X-Generator: Launchpad (build 18505)\n"

#: usr/lib/xentaos/xentaSources/xentaSources.py:42
msgid "You are about to remove the following PPA:"
msgstr "คุณกำลังจะถอดถอน PPA ต่อไปนี้:"

#: usr/lib/xentaos/xentaSources/xentaSources.py:45
#: usr/lib/xentaos/xentaSources/xentaSources.py:121
#, python-format
msgid " More info: %s"
msgstr " ข้อมูลเพิ่มเติม: %s"

#: usr/lib/xentaos/xentaSources/xentaSources.py:49
#: usr/lib/xentaos/xentaSources/xentaSources.py:125
msgid "Press Enter to continue or Ctrl+C to cancel"
msgstr "กด Enter เพื่อดำเนินการต่อหรือกด Ctrl+C เพื่อยกเลิก"

#: usr/lib/xentaos/xentaSources/xentaSources.py:53
#: usr/lib/xentaos/xentaSources/xentaSources.py:129
msgid "Unable to prompt for response.  Please run with -y"
msgstr "ไม่สามารถรอให้ตอบสนองได้ กรุณาเรียกด้วย -y"

#: usr/lib/xentaos/xentaSources/xentaSources.py:57
msgid "Cancelling..."
msgstr "กำลังยกเลิก..."

#: usr/lib/xentaos/xentaSources/xentaSources.py:60
#, python-format
msgid "Cannot get info about PPA: '%s'."
msgstr "ไม่สามารถรับข้อมูลเกี่ยวกับ PPA: '%s'"

#: usr/lib/xentaos/xentaSources/xentaSources.py:80
#, python-format
msgid "failed to remove PPA: '%s'"
msgstr "การถอดถอน PPA ล้มเหลว '%s'"

#: usr/lib/xentaos/xentaSources/xentaSources.py:97
#, python-format
msgid "failed to remove repository: '%s'"
msgstr "การลบคลังแพกเกจล้มเหลว: '%s'"

#: usr/lib/xentaos/xentaSources/xentaSources.py:104
msgid "Adding PPAs is not supported"
msgstr "ไม่รองรับการเพิ่ม PPA"

#: usr/lib/xentaos/xentaSources/xentaSources.py:111
#: usr/lib/xentaos/xentaSources/xentaSources.py:1068
#, python-format
msgid "Cannot add PPA: '%s'."
msgstr "ไม่สามารถเพิ่ม PPA ได้: '%s'"

#: usr/lib/xentaos/xentaSources/xentaSources.py:115
msgid "Adding private PPAs is not supported currently"
msgstr "ยังไม่รองรับการเพิ่ม PPA ส่วนตัวในขณะนี้"

#: usr/lib/xentaos/xentaSources/xentaSources.py:118
msgid "You are about to add the following PPA:"
msgstr "คุณกำลังจะเพิ่ม PPA ต่อไปนี้:"

#: usr/lib/xentaos/xentaSources/xentaSources.py:177
#: usr/lib/xentaos/xentaSources/xentaSources.py:180
#, python-format
msgid "This PPA does not support %s"
msgstr "PPA นี้ไม่รองรับ %s"

#: usr/lib/xentaos/xentaSources/xentaSources.py:328
#: usr/lib/xentaos/xentaSources/xentaSources.py:356
msgid "Sources"
msgstr "แหล่งข้อมูล"

#: usr/lib/xentaos/xentaSources/xentaSources.py:335
msgid "CD-ROM (Installation Disc)"
msgstr "ซีดีรอม (แผ่นติดตั้ง)"

#: usr/lib/xentaos/xentaSources/xentaSources.py:375
msgid ""
"Linux Mint uses Romeo to publish packages which are not tested. Once these "
"packages are tested, they are then moved to the official repositories. "
"Unless you are participating in beta-testing, you should not enable this "
"repository. Are you sure you want to enable Romeo?"
msgstr ""
"ลินุกซ์มินต์ใช้ Romeo เผยแพร่แพกเกจที่ไม่ได้ผ่านการทดสอบ "
"เมื่อแพกเกจเหล่านี้ถูกทดสอบแล้ว "
"จะถูกย้ายไปยังพื้นที่จัดเก็บข้อมูลอย่างเป็นทางการ "
"นอกจากว่าคุณจะมีส่วนร่วมในการทดสอบแพกเกจรุ่นทดลอง "
"คุณไม่ควรเปิดใช้งานแหล่งเก็บข้อมูลนี้ คุณต้องการที่จะเปิดใช้งาน Romeo "
"หรือไม่?"

#: usr/lib/xentaos/xentaSources/xentaSources.py:403
msgid "Select a mirror"
msgstr "เลือก mirror"

#: usr/lib/xentaos/xentaSources/xentaSources.py:414
msgid "Country"
msgstr "ประเทศ"

#: usr/lib/xentaos/xentaSources/xentaSources.py:419
msgid "URL"
msgstr "ที่อยู่ URL"

#: usr/lib/xentaos/xentaSources/xentaSources.py:424
msgid "Speed"
msgstr "ความเร็ว"

#: usr/lib/xentaos/xentaSources/xentaSources.py:447
msgid "Worldwide"
msgstr "ทั่วไป"

#: usr/lib/xentaos/xentaSources/xentaSources.py:520
#: usr/lib/xentaos/xentaSources/xentaSources.py:534
msgid "kB/s"
msgstr "กิโลไบต์/วินาที"

#: usr/lib/xentaos/xentaSources/xentaSources.py:523
msgid "MB/s"
msgstr "เมกะไบต์/วินาที"

#: usr/lib/xentaos/xentaSources/xentaSources.py:526
msgid "GB/s"
msgstr "กิกะไบต์/วินาที"

#: usr/lib/xentaos/xentaSources/xentaSources.py:567
msgid "Obsolete"
msgstr "เลิกใช้แล้ว"

#: usr/lib/xentaos/xentaSources/xentaSources.py:570
msgid "Unreachable"
msgstr "ไม่สามารถเข้าถึงได้"

#: usr/lib/xentaos/xentaSources/xentaSources.py:691 generate_desktop_files:27
#: generate_desktop_files:42
msgid "Software Sources"
msgstr "แหล่งที่มาของซอฟต์แวร์"

#: usr/lib/xentaos/xentaSources/xentaSources.py:708
msgid "Backported packages"
msgstr "แพกเกจที่ถูกย้ายกลับ"

#: usr/lib/xentaos/xentaSources/xentaSources.py:710
msgid "Unstable packages"
msgstr "แพกเกจไม่แน่นอน"

#: usr/lib/xentaos/xentaSources/xentaSources.py:723
#: usr/lib/xentaos/xentaSources/xentaSources.py:1389
msgid "No action required"
msgstr "ไม่จำเป็นต้องมีการกระทำ"

#: usr/lib/xentaos/xentaSources/xentaSources.py:725
msgid "Official repositories"
msgstr "พื้นที่จัดเก็บข้อมูลทางการ"

#: usr/lib/xentaos/xentaSources/xentaSources.py:726
msgid "PPAs"
msgstr "PPA"

#: usr/lib/xentaos/xentaSources/xentaSources.py:727
msgid "Additional repositories"
msgstr "พื้นที่จัดเก็บข้อมูลเพิ่มเติม"

#: usr/lib/xentaos/xentaSources/xentaSources.py:728
msgid "Authentication keys"
msgstr "รหัสยืนยันตัวบุคคล"

#: usr/lib/xentaos/xentaSources/xentaSources.py:729
msgid "Maintenance"
msgstr "บำรุงรักษา"

#: usr/lib/xentaos/xentaSources/xentaSources.py:731
msgid "Mirrors"
msgstr "มิเรอร์ต่าง ๆ"

#: usr/lib/xentaos/xentaSources/xentaSources.py:732
msgid "Main"
msgstr "หลัก"

#: usr/lib/xentaos/xentaSources/xentaSources.py:733
msgid "Base"
msgstr "ฐาน"

#: usr/lib/xentaos/xentaSources/xentaSources.py:734
#: usr/lib/xentaos/xentaSources/xentaSources.py:735
msgid "Select a faster server..."
msgstr "เลือกผู้ให้บริการที่เร็วกว่า..."

#: usr/lib/xentaos/xentaSources/xentaSources.py:737
msgid "Optional components"
msgstr "คอมโพเนนต์ที่ไม่จำเป็น"

#: usr/lib/xentaos/xentaSources/xentaSources.py:738
msgid "Source code"
msgstr "ซอร์สโค้ด"

#: usr/lib/xentaos/xentaSources/xentaSources.py:740
msgid "Add a new PPA..."
msgstr "เพิ่ม PPA ใหม่..."

#: usr/lib/xentaos/xentaSources/xentaSources.py:741
#: usr/lib/xentaos/xentaSources/xentaSources.py:747
msgid "Edit URL..."
msgstr "แก้ไขที่อยู่ URL..."

#: usr/lib/xentaos/xentaSources/xentaSources.py:742
#: usr/lib/xentaos/xentaSources/xentaSources.py:748
#: usr/lib/xentaos/xentaSources/xentaSources.py:752
#: usr/lib/xentaos/xentaSources/foreign_packages.py:41
msgid "Remove"
msgstr "ลบคู่สนทนา"

#: usr/lib/xentaos/xentaSources/xentaSources.py:743
msgid "Open PPA"
msgstr "เปิด PPA"

#: usr/lib/xentaos/xentaSources/xentaSources.py:744
msgid "Look inside the PPA and install packages it provides"
msgstr "ดูข้อมูลภายใน PPA และติดตัแพคเกจที่มี"

#: usr/lib/xentaos/xentaSources/xentaSources.py:746
msgid "Add a new repository..."
msgstr "เพิ่มพื้นที่จัดเก็บข้อมูลใหม่..."

#: usr/lib/xentaos/xentaSources/xentaSources.py:750
msgid "Import key file..."
msgstr "นำเข้าแฟ้มกุญแจ..."

#: usr/lib/xentaos/xentaSources/xentaSources.py:751
msgid "Download a key..."
msgstr "ดาวน์โหลดกุญแจ..."

#: usr/lib/xentaos/xentaSources/xentaSources.py:754
msgid "Fix MergeList problems"
msgstr "แก้ไขปัญหาการรวมรายการ"

#: usr/lib/xentaos/xentaSources/xentaSources.py:755
msgid ""
"If you experience MergeList problems, click this button to solve the problem."
msgstr "หากคุณประสบปัญหาการรวมรายการ ให้คลิกปุ่มนี้เพื่อแก้ไขปัญหานี้"

#: usr/lib/xentaos/xentaSources/xentaSources.py:756
msgid "Purge residual configuration"
msgstr "การกำหนดค่าที่เหลือล้าง"

#: usr/lib/xentaos/xentaSources/xentaSources.py:757
msgid ""
"Packages sometimes leave configuration files on the system even after they "
"are removed."
msgstr ""
"บางแพกเกจอาจทิ้งแฟ้มการกำหนดค่าในระบบเป็นบางครั้งแม้ว่าแพกเกจเหล่านั้นลบไปแล้"
"ว"

#: usr/lib/xentaos/xentaSources/xentaSources.py:758
msgid "Remove foreign packages"
msgstr "ลบแพคเกจต่างด้าว"

#: usr/lib/xentaos/xentaSources/xentaSources.py:759
msgid ""
"Packages which do not come from known repositories are listed here and can "
"be removed."
msgstr ""
"แพคเกจที่ไม่ได้มาจากแหล่งข้อมูลที่รู้จักจะปรากฏชื่อบนรายการนี้ "
"และคุณสามารถเลือกที่จะถอดถอนได้"

#: usr/lib/xentaos/xentaSources/xentaSources.py:760
msgid "Downgrade foreign packages"
msgstr "ดาวน์เกรดแพคเกจต่างด้าว"

#: usr/lib/xentaos/xentaSources/xentaSources.py:761
msgid ""
"Packages which version does not come from known repositories are listed here "
"and can be downgraded."
msgstr ""
"แพคเกจที่มีเวอร์ชันใหม่ที่ไม่ได้มาจากแหล่งข้อมูลที่รู้จักจะปรากฏชื่อบนรายการน"
"ี้ และคุณสามารถเลือกที่จะดาวน์เกรดได้"

#: usr/lib/xentaos/xentaSources/xentaSources.py:767
msgid "Enable source code repositories"
msgstr "เปิดใช้งานพื้นที่จัดเก็บข้อมูลซอร์สโค้ด"

#: usr/lib/xentaos/xentaSources/xentaSources.py:777
msgid ""
"Warning: Unstable packages can introduce regressions and negatively impact "
"your system. Please do not enable these options in Linux Mint unless it was "
"suggested by the development team."
msgstr ""
"คำเตือน: แพกเกจที่ไม่เสถียรอาจมีจุดบกพร่องซึ่งอาจมีผลต่อระบบของคุณในทางลบได้ "
"โปรดอย่าเปิดใช้งานตัวเลือกเหล่านี้ใน Linux Mint "
"นอกจากจะได้รับการแนะนำโดยทีมงานผู้พัฒนา"

#: usr/lib/xentaos/xentaSources/xentaSources.py:841
#: usr/lib/xentaos/xentaSources/xentaSources.py:865
msgid "Enabled"
msgstr "เปิดใช้งาน"

#: usr/lib/xentaos/xentaSources/xentaSources.py:847
#: usr/lib/xentaos/xentaSources/ppa_browser.py:40
msgid "PPA"
msgstr "PPA"

#: usr/lib/xentaos/xentaSources/xentaSources.py:871
msgid "Repository"
msgstr "พื้นที่จัดเก็บข้อมูล"

#: usr/lib/xentaos/xentaSources/xentaSources.py:887
msgid "Key"
msgstr "กุญแจ"

#: usr/lib/xentaos/xentaSources/xentaSources.py:900
msgid "Restore the default settings"
msgstr "คืนการตั้งค่าเดิม"

#: usr/lib/xentaos/xentaSources/xentaSources.py:901
msgid "Restore the official repositories to their default settings"
msgstr "คืนการตั้งค่าเดิมให้แก่พื้นที่จัดเก็บข้อมูลเป็นทางการ"

#: usr/lib/xentaos/xentaSources/xentaSources.py:986
msgid "There is no more residual configuration on the system."
msgstr "ไม่มีการกำหนดค่าที่ตกค้างอยู่ในระบบแล้ว"

#: usr/lib/xentaos/xentaSources/xentaSources.py:992
msgid "The problem was fixed. Please reload the cache."
msgstr "ปัญหานี้ได้แก้ไขสำเร็จแล้ว กรุณาโหลดแคชใหม่อีกครั้ง"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1018
msgid "Open.."
msgstr "เปิด..."

#: usr/lib/xentaos/xentaSources/xentaSources.py:1034
msgid ""
"Please enter the 8 characters of the public key you want to download from "
"keyserver.ubuntu.com:"
msgstr ""
"กรุณาป้อนอักขระ 8 ตัวของกุญแจสาธารณะที่คุณต้องการดาวน์โหลดจากเว็บไซต์ "
"keyserver.ubuntu.com:"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1047
msgid "Are you sure you want to permanently remove this key?"
msgstr "คุณต้องการจะลบกุญแจนี้ถาวรเลยหรือไม่?"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1061
msgid "Please enter the name of the PPA you want to add:"
msgstr "กรุณาป้อนชื่อของ PPA ที่คุณจะเพิ่มเข้า:"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1114
msgid "Edit the URL of the PPA"
msgstr "แก้ไขที่อยู่ URL ของ PPA นี้"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1124
msgid "Are you sure you want to permanently remove this PPA?"
msgstr "คุณต้องการลบ PPA นี้อย่างถาวรเลยหรือไม่?"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1162
msgid ""
"The content of this PPA is not available. Please refresh the cache and try "
"again."
msgstr "เนื้อหาใน PPA นี้ใช้ไม่ได้ โปรดลองรีเฟรชแคช และลองอีกครั้ง"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1176
msgid "Please enter the name of the repository you want to add:"
msgstr "กรุณาป้อนชื่อพื้นที่จัดเก็บข้อมูลที่คุณจะเพิ่มเข้า:"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1195
msgid "Edit the URL of the repository"
msgstr "แก้ไขที่อยู่ URL ของพื้นที่จัดเก็บข้อมูล"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1205
msgid "Are you sure you want to permanently remove this repository?"
msgstr "คุณต้องการลบพื้นที่จัดเก็บข้อมูลนี้อย่างถาวรเลยหรือไม่?"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1383
msgid "Update the cache"
msgstr "ปรับปรุงแคช"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1384
msgid "Click here to update your APT cache with your new sources"
msgstr ""
"คลิกที่นี่เพื่อปรับปรุงแคช APT ของคุณพร้อมแหล่งเก็บข้อมูลที่ใหม่ของคุณ"

#: usr/lib/xentaos/xentaSources/xentaSources.py:1390
msgid "Your APT cache is up to date"
msgstr "แคช APT ของคุณเป็นรุ่นล่าสุดแล้ว"

#: usr/lib/xentaos/xentaSources/ppa_browser.py:46
msgid "Install"
msgstr "ติดตั้ง"

#: usr/lib/xentaos/xentaSources/ppa_browser.py:49
#: usr/lib/xentaos/xentaSources/foreign_packages.py:50
msgid "Cancel"
msgstr "ยกเลิก"

#: usr/lib/xentaos/xentaSources/ppa_browser.py:50
msgid ""
"This PPA provides the following packages. Please select the ones you want to "
"install:"
msgstr "PPA นี้จะจัดหาแพคเกจต่อไปนี้ กรุณาเลือกแพคเกจที่คุณจะติดตั้ง:"

#: usr/lib/xentaos/xentaSources/ppa_browser.py:81
#, python-format
msgid "version %s already installed"
msgstr "ติดตั้งเวอร์ชัน %s แล้ว"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:31
msgid "Foreign packages"
msgstr "แพคเกจต่างด้าว"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:38
msgid "Downgrade"
msgstr "เลื่อนลง"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:39
msgid ""
"The version of the following packages doesn't match the one from the "
"repositories:"
msgstr "เวอร์ชันของแพคเกจต่อไปนี้ไม่ตรงกับรายการปัจจุบันจากแหล่งข้อมูล:"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:42
msgid ""
"The packages below are installed on your computer but not present in the "
"repositories:"
msgstr ""
"แพคเกจด้านล่างถูกติดตั้งไว้บนคอมพิวเตอร์ของคุณแล้ว "
"แต่ไม่ปรากฏอยู่ในแหล่งข้อมูล:"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:47
#: usr/lib/xentaos/xentaSources/foreign_packages.py:190
msgid "Select All"
msgstr "เลือกทั้งหมด"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:51
msgid "WARNING"
msgstr "คำเตือน"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:52
msgid ""
"Review the information below very carefully before validating the command:"
msgstr ""
"โปรดตรวจสอบข้อมูลด้านล่างอย่างละเอียดก่อนตรวจสอบความถูกต้องของคำสั่ง:"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:69
msgid "Package"
msgstr "หีบห่อ"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:74
msgid "Installed version"
msgstr "รุ่นที่ติดตั้งแล้ว"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:80
msgid "Repository version"
msgstr "รุ่นของแหล่งข้อมูล"

#: usr/lib/xentaos/xentaSources/foreign_packages.py:193
msgid "Clear"
msgstr "ล้าง"

#: usr/bin/software-sources:9
msgid "Please enter your password to configure the software sources"
msgstr "กรุณาป้อนรหัสผ่านของคุณเพื่อกำหนดค่าแหล่งซอฟต์แวร์นี้"

#: usr/bin/add-apt-repository:10
msgid "Error: must run as root"
msgstr "ผิดพลาด: ต้องทำการในฐานะ root"

#: usr/bin/add-apt-repository:23
msgid "Error: need a repository as argument"
msgstr "ผิดพลาด: ต้องการแหล่งจัดเก็บข้อมูลไว้เป็นข้อพิสูจน์"

#: generate_desktop_files:27 generate_desktop_files:42
msgid "Configure the sources for installable software and updates"
msgstr "ปรับแต่งแหล่งของซอฟต์แวร์ที่ใช้ในการติดตั้งและปรับปรุงรุ่น"
